#!/bin/bash

status="$(curl -Is --insecure https://${HOSTNAME}.${INSTRUQT_PARTICIPANT_ID}.instruqt.io/entando-de-app/en/tableau.page | head -1)"
validate=( $status )
if [ ${validate[-2]} == "200" ]; then
  echo "OK"
else
  echo "NOT RESPONDING"
  fail-message "Tableau Page is not created, Please follow the instruction to install and create new page with tableau"  
fi