version: "3"
virtualmachines:
- name: named-k3s
  image: entandodev/named-k3s-preloaded-ca-ent-abpatch-pro-vmware
  shell: /bin/bash
  machine_type: n1-standard-2
  allow_external_ingress:
  - https
  - http
  - high-ports
